#pragma once

#define SPLIT_MAX_CONNECTION_ERRORS 10
#define MASTER_LEFT
#define EE_HANDS

#define USB_VBUS_PIN GP24

#define SERIAL_USART_DRIVER SIOD1
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP4
#define SERIAL_USART_RX_PIN GP5
#define SERIAL_USART_PIN_SWAP
